### ISSUE TITLE
[UI Update] remove non-necessary information in setting page

### ISSUE THREAD

**Issue by wcchung** [numbersprotocol/lifebox#11]
**Update Purpose**
將設定頁面裡不必要的資訊移除，或改為 Optional

**UI Suggestion**

1. 將性別、生日移到最上方 (語言的下方)，此兩欄為必要
2. 將名字、姓氏、電子郵件刪除，或移至下方並改為 Optional
3. 新增 "身高" 並且為 Optional
4. 將國籍、城市刪除

**More Description (if any)**

1. 性別、生日對於疾病的追蹤與病人分類是重要的
2. 個人資訊部分非必要，可刪除或保留但是註明為 Optional
3. 將每日記錄的 "身高" 移到設定頁面
4. 國籍、城市會造成 confuse，不知道要填寫戶籍地還是居住地，並且和疾病無關

https://docs.google.com/presentation/d/19C7nkjTdKLynokwpUXKjvaJbtQS1Jwm7OY6EjQZfrPs/edit#slide=id.g87ffbe1d9a_0_0
可參考上述檔案 p.12

**Comment by tammyyang** [comment]
https://github.com/MyDataTaiwan/mylog14/issues/174
