### ISSUE TITLE
[UI Update] Enlarge font size

### ISSUE THREAD

**Issue by wcchung** [numbersprotocol/lifebox#15]
**Update Purpose**
Enlarge font size

**UI Suggestion**

**More Description (if any)**

Because our user are mostly elder person, the font size now is too small for them.

**Comment by tammyyang** [comment]
@wcchung please close this issue and add one FR in MyLog "can choose font size, small, medium, large in settings" and put it in backlog milestone

**Comment by tammyyang** [comment]
https://github.com/MyDataTaiwan/mylog14/issues/178
